"""empty message

Revision ID: 0f7c3e36d7f8
Revises: 14f3de00f9ff
Create Date: 2026-05-19 17:10:31.758128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7c3e36d7f8'
down_revision: Union[str, Sequence[str], None] = '14f3de00f9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bannerpities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('banner_id', sa.Integer(), nullable=False),
    sa.Column('pity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banner_id'], ['banners.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'banner_cards', 'cards', ['card_id'], ['id'])
    op.create_foreign_key(None, 'banners', 'verses', ['verse_id'], ['id'])
    op.create_foreign_key(None, 'battle_inventories', 'cards', ['hrono_id'], ['id'])
    op.create_foreign_key(None, 'battle_inventories', 'cards', ['common_id'], ['id'])
    op.create_foreign_key(None, 'battle_inventories', 'cards', ['mythic_id'], ['id'])
    op.create_foreign_key(None, 'battle_inventories', 'cards', ['legend_id'], ['id'])
    op.create_foreign_key(None, 'battle_inventories', 'cards', ['uncommon_id'], ['id'])
    op.create_foreign_key(None, 'titles', 'rarities', ['rarity_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'cards', ['card_id'], ['id'])
    op.create_foreign_key(None, 'usercards', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('users', 'pity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'usercards', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'titles', type_='foreignkey')
    op.drop_constraint(None, 'battle_inventories', type_='foreignkey')
    op.drop_constraint(None, 'battle_inventories', type_='foreignkey')
    op.drop_constraint(None, 'battle_inventories', type_='foreignkey')
    op.drop_constraint(None, 'battle_inventories', type_='foreignkey')
    op.drop_constraint(None, 'battle_inventories', type_='foreignkey')
    op.drop_constraint(None, 'banners', type_='foreignkey')
    op.drop_constraint(None, 'banner_cards', type_='foreignkey')
    op.drop_table('bannerpities')
    # ### end Alembic commands ###
