"""Added Title table

Revision ID: 0ff1f98e367b
Revises: 23158480bd15
Create Date: 2026-04-24 14:37:30.833524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff1f98e367b'
down_revision: Union[str, Sequence[str], None] = '23158480bd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('titles', 'target1',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.alter_column('titles', 'target2',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('titles', 'target2',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
    op.alter_column('titles', 'target1',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    # ### end Alembic commands ###
