"""empty message

Revision ID: 14f3de00f9ff
Revises: a615a0c3ab68
Create Date: 2026-05-19 10:31:16.895512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f3de00f9ff'
down_revision: Union[str, Sequence[str], None] = 'a615a0c3ab68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
                    existing_type=sa.String(length=100),
                    type_=sa.Text(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
                    existing_type=sa.Text(),
                    type_=sa.String(length=100),
                    existing_nullable=False)
    # ### end Alembic commands ###
