"""Added Title table

Revision ID: 23158480bd15
Revises: c7736f044bfe
Create Date: 2026-04-24 14:35:26.786521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23158480bd15'
down_revision: Union[str, Sequence[str], None] = 'c7736f044bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('buff1', sa.Integer(), nullable=False),
    sa.Column('target1', sa.CHAR(), nullable=False),
    sa.Column('buff2', sa.Integer(), nullable=True),
    sa.Column('target2', sa.CHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('profiles', sa.Column('title_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    op.create_foreign_key(None, 'profiles', 'titles', ['title_id'], ['id'])
    op.alter_column('trades', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('trades', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trades', 'partner_card',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'trades', 'cards', ['card_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trades_card_id_fkey', 'trades', type_='foreignkey')
    op.drop_constraint('trades_user_id_fkey', 'trades', type_='foreignkey')
    op.alter_column('trades', 'partner_card',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('trades', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trades', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('profiles_title_id_fkey', 'profiles', type_='foreignkey')
    op.drop_constraint('profiles_user_id_key', 'profiles', type_='unique')
    op.drop_column('profiles', 'title_id')
    op.drop_table('titles')
    # ### end Alembic commands ###
