"""empty message

Revision ID: 304589cfd9c4
Revises: c66d2349a83d
Create Date: 2026-06-16 14:20:13.916763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304589cfd9c4'
down_revision: Union[str, Sequence[str], None] = 'c66d2349a83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add card_type column with default value for existing records
    op.add_column('cards', sa.Column('card_type', sa.Enum('Стандартная', 'Сезонная', name='card_type_enum'), nullable=True))
    op.execute("UPDATE cards SET card_type = 'Стандартная' WHERE card_type IS NULL")
    op.alter_column('cards', 'card_type', nullable=False)

    # Add season_balance column with default value for existing records
    op.add_column('users', sa.Column('season_balance', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET season_balance = 0 WHERE season_balance IS NULL")
    op.alter_column('users', 'season_balance', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'season_balance')
    op.drop_column('cards', 'card_type')
    # ### end Alembic commands ###
