"""add pvp_wins field

Revision ID: 4217ee8be0d8
Revises: a1b2c3d4e5f7
Create Date: 2026-04-05 10:28:38.627720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4217ee8be0d8'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'verse_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('cards', 'rarity_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cards', 'shiny',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cards', 'can_drop',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(None, 'cards', 'rarities', ['rarity_name'], ['name'])
    op.create_foreign_key(None, 'cards', 'verses', ['verse_name'], ['name'])
    op.create_foreign_key(None, 'clan_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promo_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'referrals', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'referrals', 'users', ['referral_id'], ['id'])
    op.alter_column('trades', 'partner_card',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('trades', 'partner_added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('usercards_user_id_card_id_unique'), 'usercards', type_='unique')
    op.create_foreign_key(None, 'usercards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('pvp_wins', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vip_subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vip_subscriptions', type_='foreignkey')
    op.drop_column('users', 'pvp_wins')
    op.drop_constraint(None, 'usercards', type_='foreignkey')
    op.create_unique_constraint(op.f('usercards_user_id_card_id_unique'), 'usercards', ['user_id', 'card_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('trades', 'partner_added_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('trades', 'partner_card',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'promo_users', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'clan_members', type_='foreignkey')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.alter_column('cards', 'can_drop',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('cards', 'shiny',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('cards', 'rarity_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cards', 'verse_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
