"""Added droppable in Titles

Revision ID: 4e7fa755f4f8
Revises: 7bb8c836038e
Create Date: 2026-05-11 10:23:19.616590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7fa755f4f8'
down_revision: Union[str, Sequence[str], None] = '7bb8c836038e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('titles', sa.Column('droppable', sa.Boolean(), nullable=True))

    # Then update all existing rows to have the default value
    op.execute("UPDATE titles SET droppable = TRUE")

    # Finally alter the column to be non-nullable
    op.alter_column('titles', 'droppable', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'droppable')
    # ### end Alembic commands ###
