"""Added Title table

Revision ID: 7bb8c836038e
Revises: 0ff1f98e367b
Create Date: 2026-04-24 14:56:52.209294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb8c836038e'
down_revision: Union[str, Sequence[str], None] = '0ff1f98e367b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('rarity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'titles', 'rarities', ['rarity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('titles_rarity_id_fkey', 'titles', type_='foreignkey')
    op.drop_column('titles', 'rarity_id')
    # ### end Alembic commands ###
