"""add_partner_card_id_to_trade

Revision ID: 9d1e1f6f4e38
Revises: 06fc6cdda92e
Create Date: 2026-03-01 01:46:02.664206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1e1f6f4e38'
down_revision: Union[str, Sequence[str], None] = '06fc6cdda92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('partner_card_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'partner_card_id')
    # ### end Alembic commands ###
