"""empty message

Revision ID: a615a0c3ab68
Revises: e1943d4c5927
Create Date: 2026-05-19 10:16:56.847762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a615a0c3ab68'
down_revision: Union[str, Sequence[str], None] = 'e1943d4c5927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pity',
                    existing_type=sa.Integer(),
                    server_default='0',
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pity',
                    existing_type=sa.Integer(),
                    server_default='100',
                    nullable=False)
    # ### end Alembic commands ###
