"""empty message

Revision ID: ad2b11fdd81a
Revises: 0f7c3e36d7f8
Create Date: 2026-05-19 21:48:33.994242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2b11fdd81a'
down_revision: Union[str, Sequence[str], None] = '0f7c3e36d7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'banner_cards', 'cards', ['card_id'], ['id'])
    op.add_column('bannerpities', sa.Column('ssr_pity', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('bannerpities', sa.Column('sr_pity', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('bannerpities', sa.Column('s_pity', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('bannerpities', 'pity')
    op.create_foreign_key(None, 'banners', 'verses', ['verse_id'], ['id'])
    op.create_foreign_key(None, 'battle_inventories', 'cards', ['mythic_id'], ['id'])
    op.create_foreign_key(None, 'battle_inventories', 'cards', ['legend_id'], ['id'])
    op.create_foreign_key(None, 'battle_inventories', 'cards', ['common_id'], ['id'])
    op.create_foreign_key(None, 'battle_inventories', 'cards', ['uncommon_id'], ['id'])
    op.create_foreign_key(None, 'battle_inventories', 'cards', ['hrono_id'], ['id'])
    op.create_foreign_key(None, 'titles', 'rarities', ['rarity_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'cards', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'titles', type_='foreignkey')
    op.drop_constraint(None, 'battle_inventories', type_='foreignkey')
    op.drop_constraint(None, 'battle_inventories', type_='foreignkey')
    op.drop_constraint(None, 'battle_inventories', type_='foreignkey')
    op.drop_constraint(None, 'battle_inventories', type_='foreignkey')
    op.drop_constraint(None, 'battle_inventories', type_='foreignkey')
    op.drop_constraint(None, 'banners', type_='foreignkey')
    op.add_column('bannerpities', sa.Column('pity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bannerpities', 's_pity')
    op.drop_column('bannerpities', 'sr_pity')
    op.drop_column('bannerpities', 'ssr_pity')
    op.drop_constraint(None, 'banner_cards', type_='foreignkey')
    # ### end Alembic commands ###
