"""empty message

Revision ID: b952395b46fe
Revises: e528d47dba2b
Create Date: 2026-03-04 16:07:09.374120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b952395b46fe'
down_revision: Union[str, Sequence[str], None] = 'e528d47dba2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'describe',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'describe',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    # ### end Alembic commands ###
