"""empty message

Revision ID: c3658643bec0
Revises: 028ea3079a83
Create Date: 2026-03-01 12:20:04.301741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'c3658643bec0'
down_revision: Union[str, Sequence[str], None] = '028ea3079a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name: str, column_name: str) -> bool:
    """Проверяет существование столбца в таблице."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем partner_added_at только если он не существует
    if not column_exists('trades', 'partner_added_at'):
        op.add_column('trades', sa.Column('partner_added_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем partner_added_at только если он существует
    if column_exists('trades', 'partner_added_at'):
        op.drop_column('trades', 'partner_added_at')
    # ### end Alembic commands ###
