"""Added visible field for profiles

Revision ID: c7736f044bfe
Revises: b14a6040d616
Create Date: 2026-04-23 13:33:59.433565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7736f044bfe'
down_revision: Union[str, Sequence[str], None] = 'b14a6040d616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('visible', sa.Boolean(), nullable=False, server_default='true'))
    op.drop_index(op.f('ix_pvp_search_queue_user_id'), table_name='pvp_search_queue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pvp_search_queue_user_id'), 'pvp_search_queue', ['user_id'], unique=False)
    op.drop_column('profiles', 'visible')
    # ### end Alembic commands ###
