"""add battle_inventories table

Revision ID: c8b11f3ec3a7
Revises: 35a67f845bfd
Create Date: 2026-04-05 10:59:24.596880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b11f3ec3a7'
down_revision: Union[str, Sequence[str], None] = '35a67f845bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle_inventories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('common_id', sa.Integer(), nullable=True),
    sa.Column('uncommon_id', sa.Integer(), nullable=True),
    sa.Column('mythic_id', sa.Integer(), nullable=True),
    sa.Column('legend_id', sa.Integer(), nullable=True),
    sa.Column('hrono_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['common_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['hrono_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['legend_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['mythic_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['uncommon_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle_inventories')
    # ### end Alembic commands ###
