"""empty message

Revision ID: 028ea3079a83
Revises: 9d1e1f6f4e38
Create Date: 2026-03-01 11:53:46.249185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '028ea3079a83'
down_revision: Union[str, Sequence[str], None] = '9d1e1f6f4e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name: str, column_name: str) -> bool:
    """Проверяет существование столбца в таблице."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем partner_id только если он не существует
    if not column_exists('trades', 'partner_id'):
        op.add_column('trades', sa.Column('partner_id', sa.BigInteger(), nullable=True))
    
    # Добавляем partner_card только если он не существует
    if not column_exists('trades', 'partner_card'):
        op.add_column('trades', sa.Column('partner_card', sa.BigInteger(), nullable=True))
    
    # Удаляем partner_card_id только если он существует
    if column_exists('trades', 'partner_card_id'):
        op.drop_column('trades', 'partner_card_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Восстанавливаем partner_card_id только если он не существует
    if not column_exists('trades', 'partner_card_id'):
        op.add_column('trades', sa.Column('partner_card_id', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # Удаляем partner_card только если он существует
    if column_exists('trades', 'partner_card'):
        op.drop_column('trades', 'partner_card')
    
    # Удаляем partner_id только если он существует
    if column_exists('trades', 'partner_id'):
        op.drop_column('trades', 'partner_id')
    # ### end Alembic commands ###
