"""empty message

Revision ID: 028ea3079a83
Revises: 9d1e1f6f4e38
Create Date: 2026-03-01 11:53:46.249185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '028ea3079a83'
down_revision: Union[str, Sequence[str], None] = '9d1e1f6f4e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('partner_id', sa.BigInteger(), nullable=True))
    op.add_column('trades', sa.Column('partner_card', sa.BigInteger(), nullable=True))
    op.drop_column('trades', 'partner_card_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('partner_card_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('trades', 'partner_card')
    op.drop_column('trades', 'partner_id')
    # ### end Alembic commands ###
