"""empty message

Revision ID: 06fc6cdda92e
Revises: f2ac6d7d08b1
Create Date: 2026-02-28 17:13:45.682031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fc6cdda92e'
down_revision: Union[str, Sequence[str], None] = 'f2ac6d7d08b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a temporary table with the new structure
    op.execute("""
        CREATE TABLE usercards_new (
            id SERIAL PRIMARY KEY,
            user_id BIGINT NOT NULL,
            card_id INTEGER NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE
        )
    """)
    
    # Copy data from old table to new table
    op.execute("INSERT INTO usercards_new (user_id, card_id) SELECT user_id, card_id FROM usercards")
    
    # Drop the old table
    op.drop_table('usercards')
    
    # Rename the new table to the original name
    op.rename_table('usercards_new', 'usercards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercards', 'id')
    # ### end Alembic commands ###
