"""Referrals update

Revision ID: 2348b4a4eb83
Revises: e2a7380ee076
Create Date: 2026-01-06 20:05:37.808098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2348b4a4eb83'
down_revision: Union[str, Sequence[str], None] = 'e2a7380ee076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the id column as nullable
    op.add_column('referrals', sa.Column('id', sa.Integer(), nullable=True))

    # Create a sequence for the id column
    op.execute('CREATE SEQUENCE referrals_id_seq')

    # Update existing rows to set id values from the sequence
    op.execute('''
        UPDATE referrals
        SET id = nextval('referrals_id_seq')
        WHERE id IS NULL
    ''')

    # Now make the id column non-nullable and set it as primary key with autoincrement
    op.alter_column('referrals', 'id', nullable=False)
    op.execute('ALTER SEQUENCE referrals_id_seq OWNED BY referrals.id')
    op.execute('ALTER TABLE referrals ALTER COLUMN id SET DEFAULT nextval(\'referrals_id_seq\')')

    # Drop the old composite primary key first
    op.drop_constraint('referrals_pkey', 'referrals', type_='primary')

    # Add primary key constraint
    op.create_primary_key('pk_referrals', 'referrals', ['id'])

    op.drop_constraint(op.f('fk_referrals_referral_id'), 'referrals', type_='foreignkey')
    op.drop_constraint(op.f('fk_referrals_user_id'), 'referrals', type_='foreignkey')
    op.create_foreign_key(None, 'referrals', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'referrals', 'users', ['referral_id'], ['id'])
    op.drop_column('referrals', 'rewarded')
    op.drop_column('referrals', 'created_at')
    op.drop_column('users', 'referral_yens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_yens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('referrals', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2026-01-06 16:45:45.493446+03'::timestamp with time zone"), autoincrement=False, nullable=False))
    op.add_column('referrals', sa.Column('rewarded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_referrals_user_id'), 'referrals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_referrals_referral_id'), 'referrals', 'users', ['referral_id'], ['id'], ondelete='CASCADE')
    op.drop_column('referrals', 'id')
    # ### end Alembic commands ###
