"""Remove unused fields

Revision ID: 26b208238ceb
Revises: 86579cd1dceb
Create Date: 2026-02-08 10:12:30.190992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b208238ceb'
down_revision: Union[str, Sequence[str], None] = '86579cd1dceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'referrer_reward')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referrer_reward', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
