"""Users add vip

Revision ID: 486dfaa6539c
Revises: a79ed1c9e6ba
Create Date: 2026-01-07 20:29:40.601319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486dfaa6539c'
down_revision: Union[str, Sequence[str], None] = 'a79ed1c9e6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vip', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vip')
    # ### end Alembic commands ###
