"""Rename yens into balance

Revision ID: 86579cd1dceb
Revises: cb29338b3e27
Create Date: 2026-02-05 13:20:01.361331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86579cd1dceb'
down_revision: Union[str, Sequence[str], None] = 'cb29338b3e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the columns as nullable
    op.add_column('profiles', sa.Column('joined', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE profiles SET joined = NOW()")
    op.execute("UPDATE users SET balance = 0")
    
    # Now make the columns non-nullable
    op.alter_column('profiles', 'joined', nullable=False)
    op.alter_column('users', 'balance', nullable=False)
    
    # Drop old columns
    op.drop_column('users', 'yens')
    op.drop_column('users', 'joined')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('yens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'balance')
    op.drop_column('profiles', 'joined')
    # ### end Alembic commands ###
