"""Referrals update

Revision ID: a79ed1c9e6ba
Revises: 2348b4a4eb83
Create Date: 2026-01-06 20:54:08.268820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79ed1c9e6ba'
down_revision: Union[str, Sequence[str], None] = '2348b4a4eb83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referrer_reward', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'referrer_reward')
    # ### end Alembic commands ###
