"""empty message

Revision ID: c8296f330efa
Revises: 3342f25d109d
Create Date: 2026-03-23 03:12:01.241612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8296f330efa'
down_revision: Union[str, Sequence[str], None] = '3342f25d109d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle_invеntories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle_invеntories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('common_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uncommon_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mythic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('legend_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hrono_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['common_id'], ['cards.id'], name=op.f('battle_invеntories_common_id_fkey')),
    sa.ForeignKeyConstraint(['hrono_id'], ['cards.id'], name=op.f('battle_invеntories_hrono_id_fkey')),
    sa.ForeignKeyConstraint(['legend_id'], ['cards.id'], name=op.f('battle_invеntories_legend_id_fkey')),
    sa.ForeignKeyConstraint(['mythic_id'], ['cards.id'], name=op.f('battle_invеntories_mythic_id_fkey')),
    sa.ForeignKeyConstraint(['uncommon_id'], ['cards.id'], name=op.f('battle_invеntories_uncommon_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('battle_invеntories_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('battle_invеntories_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('battle_invеntories_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
