"""remove start field

Revision ID: cb29338b3e27
Revises: 75a887100f1a
Create Date: 2026-01-27 17:28:24.722069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb29338b3e27'
down_revision: Union[str, Sequence[str], None] = '75a887100f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('start', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
