"""Add rewarded and created_at fields to referrals

Revision ID: e18aa2c91745
Revises: 
Create Date: 2026-01-06 16:45:22.906398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18aa2c91745'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('rewarded', sa.Boolean(), nullable=False))
    op.add_column('referrals', sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False))
    op.drop_index(op.f('idx_referrals_referral_id'), table_name='referrals')
    op.drop_index(op.f('idx_referrals_user_id'), table_name='referrals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_referrals_user_id'), 'referrals', ['user_id'], unique=False)
    op.create_index(op.f('idx_referrals_referral_id'), 'referrals', ['referral_id'], unique=False)
    op.drop_column('referrals', 'created_at')
    op.drop_column('referrals', 'rewarded')
    # ### end Alembic commands ###
