"""Add referral_yens field to users

Revision ID: e2a7380ee076
Revises: e18aa2c91745
Create Date: 2026-01-06 17:01:16.516430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a7380ee076'
down_revision: Union[str, Sequence[str], None] = 'e18aa2c91745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем столбец как nullable
    op.add_column('users', sa.Column('referral_yens', sa.Integer(), nullable=True))
    # Затем обновляем существующие записи, устанавливая значение по умолчанию (0)
    op.execute('UPDATE users SET referral_yens = 0 WHERE referral_yens IS NULL')
    # Наконец, делаем столбец NOT NULL
    op.alter_column('users', 'referral_yens', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_yens')
    # ### end Alembic commands ###
