"""add used_by in promo

Revision ID: f2ac6d7d08b1
Revises: 2bdca3d121b8
Create Date: 2026-02-27 13:14:11.529764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ac6d7d08b1'
down_revision: Union[str, Sequence[str], None] = '2bdca3d121b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promo_id'], ['promocodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'promo_id')
    )
    # Добавляем столбец как nullable сначала
    op.add_column('promocodes', sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True))

    # Обновляем существующие записи с значением по умолчанию (текущая дата + 1 год)
    from datetime import datetime, timedelta
    default_expire = datetime.utcnow() + timedelta(days=365)
    op.execute(
        sa.text("UPDATE promocodes SET expire_at = :expire_at WHERE expire_at IS NULL").bindparams(expire_at=default_expire)
    )

    # Теперь делаем столбец NOT NULL
    op.alter_column('promocodes', 'expire_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promocodes', 'expire_at')
    op.drop_table('promo_users')
    # ### end Alembic commands ###
