"""Free Opens

Revision ID: f482bdb2313f
Revises: ad8dc7f15876
Create Date: 2026-01-09 16:14:08.052248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f482bdb2313f'
down_revision: Union[str, Sequence[str], None] = 'ad8dc7f15876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('free_open', sa.Integer(), nullable=False,server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'free_open')
    # ### end Alembic commands ###
